# Generated by Django 4.2 on 2023-05-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='estimated_price',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
