# Generated by Django 4.2 on 2023-06-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_model_mlmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='static/images/listing1.png', upload_to='static/images/list_images'),
        ),
    ]
