# Generated by Django 4.2 on 2023-06-28 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_modeldata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='modeldata',
        ),
    ]
