# Generated by Django 4.2 on 2023-06-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_delete_modeldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='modeldata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livingAreaSqFt', models.FloatField()),
                ('numOfBathrooms', models.FloatField()),
                ('lotSizeSqFt', models.FloatField()),
                ('numOfBedrooms', models.IntegerField()),
                ('numOfStories', models.IntegerField()),
                ('numOfPhotos', models.IntegerField()),
                ('hasSpa', models.BooleanField()),
                ('hasView', models.BooleanField()),
                ('numOfPatioAndPorchFeatures', models.IntegerField()),
                ('numOfParkingFeatures', models.IntegerField()),
                ('latest_saleyear', models.IntegerField()),
                ('numOfSecurityFeatures', models.IntegerField()),
                ('latestPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
