# Generated by Django 4.2 on 2023-06-28 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_modeldata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MLModel',
        ),
    ]
